# Generated by Django 4.1 on 2022-08-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='allowed_areas',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='modules',
        ),
        migrations.AddField(
            model_name='profile',
            name='accesses',
            field=models.JSONField(default='{}'),
        ),
    ]
