# Generated by Django 4.1 on 2022-08-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_allowed_areas_remove_profile_modules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('access', models.JSONField(default='{}')),
            ],
        ),
    ]
