# Generated by Django 4.1 on 2022-08-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='icon',
        ),
        migrations.AlterField(
            model_name='access',
            name='access',
            field=models.CharField(max_length=100),
        ),
    ]
