# Generated by Django 4.1 on 2022-08-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_access_icon_alter_access_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='access',
            field=models.JSONField(default='{}'),
        ),
    ]
