# Generated by Django 4.1 on 2022-08-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
            ],
        ),
    ]
